# Configuração para usar Bun no Nixpacks
[phases.setup]
nixPkgs = [
  'nodejs-20_x',
  'bun',
  'python3',
  'gcc',
  'pkg-config',
  'pango',
  'cairo',
  'libjpeg',
  'giflib',
  'librsvg',
  'unzip'
]

[phases.install]
cmds = [
  'curl -fsSL https://bun.sh/install | bash -s "bun-v1.2.3"',
  'export PATH="$HOME/.bun/bin:$PATH"',
  'bun --version',
  'bun install --no-save'
]

[phases.build]
cmds = [
  'export PATH="$HOME/.bun/bin:$PATH"',
  'bun run build'
]

[start]
cmd = 'bun run start'

[build.args]
NODE_VERSION = "20"

[build.environment]
NODE_ENV = "production"
PORT = "6541"
BUN_INSTALL = "$HOME/.bun"
PATH = "$BUN_INSTALL/bin:$PATH"

# Desabilita o cache do Nixpacks para evitar problemas
[build]
cache = false
  
  [[phases.setup.nix.pkg]]
  name = "cairo"
  
  [[phases.setup.nix.pkg]]
  name = "jpeg"
  
  [[phases.setup.nix.pkg]]
  name = "giflib"
  
  [[phases.setup.nix.pkg]]
  name = "librsvg"
  
  [[phases.setup.nix.pkg]]
  name = "libjpeg"
  
  [[phases.setup.nix.pkg]]
  name = "libpng"
  
  [[phases.setup.nix.pkg]]
  name = "libtool"
  
  [[phases.setup.nix.pkg]]
  name = "automake"
  
  [[phases.setup.nix.pkg]]
  name = "autoconf"
  
  [[phases.setup.nix.pkg]]
  name = "nasm"
  
  [[phases.setup.nix.pkg]]
  name = "pixman"
  
  [[phases.setup.nix.pkg]]
  name = "libffi"
  
  [[phases.setup.nix.pkg]]
  name = "libyaml"
  
  [[phases.setup.nix.pkg]]
  name = "libx11"
  
  [[phases.setup.nix.pkg]]
  name = "libxrender"
  
  [[phases.setup.nix.pkg]]
  name = "libxext"
  
  [[phases.setup.nix.pkg]]
  name = "libxcb"
  
  [[phases.setup.nix.pkg]]
  name = "libxau"
  
  [[phases.setup.nix.pkg]]
  name = "libxdmcp"
  
  [[phases.setup.nix.pkg]]
  name = "libxfixes"
  
  [[phases.setup.nix.pkg]]
  name = "libxrender"
  
  [[phases.setup.nix.pkg]]
  name = "libxcb"
  
  [[phases.setup.nix.pkg]]
  name = "libxau"
  
  [[phases.setup.nix.pkg]]
  name = "libxdmcp"
  
  [[phases.setup.nix.pkg]]
  name = "libxfixes"
  
  [[phases.setup.nix.pkg]]
  name = "libxrender"
