# Configuração para usar Yarn no Nixpacks
[phases.setup]
nixPkgs = [
  'nodejs-18_x',
  'yarn',
  'python3',
  'gcc',
  'pkg-config',
  'pango',
  'cairo',
  'libjpeg',
  'giflib',
  'librsvg',
  'unzip'
]

[phases.install]
cmds = [
  'yarn set version stable',
  'yarn install --frozen-lockfile'
]

[phases.build]
cmds = [
  'yarn build'
]

[start]
cmd = 'yarn start'

[build.args]
NODE_VERSION = "20"

[build.environment]
NODE_ENV = "production"
PORT = "6541"
BUN_INSTALL = "$HOME/.bun"
PATH = "$BUN_INSTALL/bin:$PATH"

# Desabilita o cache do Nixpacks para evitar problemas
[build]
cache = false
  
  [[phases.setup.nix.pkg]]
  name = "cairo"
  
  [[phases.setup.nix.pkg]]
  name = "jpeg"
  
  [[phases.setup.nix.pkg]]
  name = "giflib"
  
  [[phases.setup.nix.pkg]]
  name = "librsvg"
  
  [[phases.setup.nix.pkg]]
  name = "libjpeg"
  
  [[phases.setup.nix.pkg]]
  name = "libpng"
  
  [[phases.setup.nix.pkg]]
  name = "libtool"
  
  [[phases.setup.nix.pkg]]
  name = "automake"
  
  [[phases.setup.nix.pkg]]
  name = "autoconf"
  
  [[phases.setup.nix.pkg]]
  name = "nasm"
  
  [[phases.setup.nix.pkg]]
  name = "pixman"
  
  [[phases.setup.nix.pkg]]
  name = "libffi"
  
  [[phases.setup.nix.pkg]]
  name = "libyaml"
  
  [[phases.setup.nix.pkg]]
  name = "libx11"
  
  [[phases.setup.nix.pkg]]
  name = "libxrender"
  
  [[phases.setup.nix.pkg]]
  name = "libxext"
  
  [[phases.setup.nix.pkg]]
  name = "libxcb"
  
  [[phases.setup.nix.pkg]]
  name = "libxau"
  
  [[phases.setup.nix.pkg]]
  name = "libxdmcp"
  
  [[phases.setup.nix.pkg]]
  name = "libxfixes"
  
  [[phases.setup.nix.pkg]]
  name = "libxrender"
  
  [[phases.setup.nix.pkg]]
  name = "libxcb"
  
  [[phases.setup.nix.pkg]]
  name = "libxau"
  
  [[phases.setup.nix.pkg]]
  name = "libxdmcp"
  
  [[phases.setup.nix.pkg]]
  name = "libxfixes"
  
  [[phases.setup.nix.pkg]]
  name = "libxrender"
