# Configurações do Bun
[install]
# Força a geração do arquivo de lock
generateLockfile = true

# Configurações de cache
[install.cache]
# Habilita o cache de instalação
enabled = true

# Configurações de registro para pacotes
[install.registry]
# Usa o registro npm padrão
url = "https://registry.npmjs.org"

# Configurações de build
[build]
# Define o diretório de saída
dist = "dist"

# Configurações de desenvolvimento
[dev]
# Porta padrão para desenvolvimento
port = 3000
