[phases.setup]
nixPkgs = [
  'nodejs-18_x',
  'python3',
  'gcc',
  'pkg-config',
  'pango',
  'cairo',
  'libjpeg',
  'giflib',
  'librsvg',
  'unzip',
  'curl',
  'wget',
  'xz',
  'unzip'
]

# Instala o Bun manualmente para garantir a versão correta
setup = "curl -fsSL https://bun.sh/install | bash -s 'bun-v1.2.3' && export BUN_INSTALL=\"$HOME/.bun\" && export PATH=\"$BUN_INSTALL/bin:$PATH\""

[phases.install]
cmds = [
  "export BUN_INSTALL=\"$HOME/.bun\" && export PATH=\"$BUN_INSTALL/bin:$PATH\"",
  "bun --version",
  "bun install --frozen-lockfile"
]

[phases.build]
cmds = [
  "export BUN_INSTALL=\"$HOME/.bun\" && export PATH=\"$BUN_INSTALL/bin:$PATH\"",
  "bun --version",
  "bun run build"
]

[start]
cmd = "export BUN_INSTALL=\"$HOME/.bun\" && export PATH=\"$BUN_INSTALL/bin:$PATH\" && bun run start"

[variables]
NODE_ENV = "production"
BUN_INSTALL = "/root/.bun"
PATH = "${BUN_INSTALL}/bin:${PATH}"
