[phases.setup]
nixPkgs = [
  'nodejs-18_x',
  'bun',
  'python3',
  'gcc',
  'pkg-config',
  'pango',
  'cairo',
  'libjpeg',
  'giflib',
  'librsvg',
  'unzip'
]

[phases.install]
cmds = ["bun install"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run start"

[variables]
NODE_ENV = "production"
BUN_INSTALL = "/root/.bun"
PATH = "${BUN_INSTALL}/bin:${PATH}"
