# Configuração para usar Bun no Nixpacks
[phases.setup]
nixPkgs = [
  'nodejs-18_x',
  'bun',
  'python3',
  'gcc',
  'pkg-config',
  'pango',
  'cairo',
  'libjpeg',
  'giflib',
  'librsvg'
]

[phases.install]
cmds = [
  'curl -fsSL https://bun.sh/install | bash -s "bun-v1.1.43"',
  'export PATH="$HOME/.bun/bin:$PATH"',
  'bun --version',
  'bun install --no-save'
]

[phases.build]
cmds = [
  'export PATH="$HOME/.bun/bin:$PATH"',
  'bun run build'
]

[start]
cmd = 'bun run start'

[build.args]
NODE_VERSION = "20"

[build.environment]
NODE_ENV = "production"
PORT = "6541"
BUN_INSTALL = "$HOME/.bun"
PATH = "$BUN_INSTALL/bin:$PATH"

# Desabilita o cache do Nixpacks para evitar problemas
[build]
cache = false